{
    'name': 'Gestión de Encuestas',
    'version': "18.0.1.0.0",
    'category': 'Industries',
    'author': 'HiddanProgrammer',
    'website': 'https://github.com/HidanProgramer/encuesta',
    'summary': 'Sistema Básico para gestionar encuestas',
    'depends': ['base'],
    'data': ['security/ir.model.access.csv',
             'views/graph_views.xml',
             'views/view_clientes_encuesta.xml',
             'views/view_encuesta_vivienda_inherit.xml',
             'views/view_encuesta_servicio_inherit.xml',
             'views/view_encuesta_nucleo_inherit.xml',
             'views/view_encuesta_actividad_inherit.xml',
             'views/view_encuesta_aspectos_inherit.xml',
             'views/view_encuesta_criterios_inherit.xml'],
    'images': ['static/description/banner.jpg'],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
}